server.port=8086

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Fix date format ? stops LocalDate/LocalDateTime showing as arrays
spring.jackson.serialization.write-dates-as-timestamps=false

# ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.jms.listener.auto-startup=true